import { StyleSheet } from 'react-native';
import { FontSize, FontFamily, Color } from '../GlobalStyles';

export const styles = StyleSheet.create({
  rectangleButtonBtn: {
    borderRadius: 3,
    height: '100%',
    width: '100%',
  },
  publicidadLayout: {
    height: 202,
    position: 'absolute',
  },
  conocerMsTypo: {
    fontSize: FontSize.size_2xs,
    top: 169,
    textAlign: 'left',
    fontFamily: FontFamily.interSemiBold,
    fontWeight: '600',
  },
  frame1Position: {
    left: 126,
    position: 'absolute',
  },
  frameLayout: {
    height: 90,
    width: 348,
    position: 'absolute',
    overflow: 'hidden',
  },
  atrsTypo: {
    fontSize: FontSize.size_xs,
    textAlign: 'left',
    color: Color.colorBlack,
    position: 'absolute',
  },
  childPosition: {
    left: '0%',
    bottom: '0%',
    right: '0%',
    top: '0%',
    position: 'absolute',
  },
  ofertasAcadmicas: {
    top: 138,
    left: 63,
    fontSize: 20,
    textAlign: 'left',
    color: Color.colorBlack,
    fontFamily: FontFamily.interSemiBold,
    fontWeight: '600',
    position: 'absolute',
  },
  publicidadChild: {
    backgroundColor: '#fafafa',
    borderStyle: 'solid',
    borderColor: '#ddd7d7',
    borderBottomWidth: 2,
    width: 265,
    left: 0,
    top: 0,
  },
  publicidad11: {
    top: 2,
    height: 151,
    left: 0,
    width: 266,
    position: 'absolute',
  },
  conocerMs: {
    left: 41,
    color: Color.colorBlack,
    fontSize: FontSize.size_2xs,
    position: 'absolute',
  },
  presionaAqu: {
    color: 'rgba(0, 141, 206, 0.85)',
    fontSize: FontSize.size_2xs,
    top: 169,
    textAlign: 'left',
    fontFamily: FontFamily.interSemiBold,
    fontWeight: '600',
  },
  publicidad: {
    left: 29,
    width: 266,
    top: 169,
    height: 202,
  },
  frameChild: {
    top: 31,
    backgroundColor: Color.colorDarkslategray,
    height: 59,
    width: 348,
    left: 0,
    position: 'absolute',
  },
  frame: {
    left: 0,
    top: 0,
  },
  googleAdsChild: {
    left: 46,
    backgroundColor: Color.colorGainsboro_100,
    width: 267,
    height: 40,
    top: 0,
    position: 'absolute',
  },
  anuncioDeGoogle: {
    top: 12,
    fontFamily: FontFamily.interRegular,
    left: 0,
  },
  frame1: {
    width: 108,
    height: 27,
    top: 0,
    overflow: 'hidden',
  },
  googleAds: {
    top: 516,
    left: -19,
  },
  tainosInTheRiver1Icon: {
    maxWidth: '100%',
    maxHeight: '100%',
    height: '100%',
    bottom: '0%',
    right: '0%',
    top: '0%',
    width: '100%',
    overflow: 'hidden',
  },
  headermainsinglewordChild: {
    backgroundColor: Color.colorDeepskyblue,
    height: '100%',
    bottom: '0%',
    right: '0%',
    top: '0%',
    width: '100%',
  },
  logoIcon: {
    top: 8,
    left: 10,
    width: 92,
    height: 34,
    position: 'absolute',
  },
  headermainsingleword: {
    width: 320,
    height: 129,
    left: 0,
    top: 0,
    position: 'absolute',
  },
  atrs: {
    top: '30.3%',
    left: '22.41%',
    fontFamily: FontFamily.interSemiBold,
    fontWeight: '600',
    fontSize: FontSize.size_xs,
  },
  btngoback: {
    top: 9,
    left: 248,
    width: 58,
    height: 33,
    position: 'absolute',
  },
  academicOffers: {
    backgroundColor: '#fff',
    flex: 1,
    height: 568,
    overflow: 'hidden',
    width: '100%',
  },
});
