import { StyleSheet } from 'react-native';
import { Color, Border, FontFamily, FontSize } from '../GlobalStyles';

export const styles = StyleSheet.create({
  searchResultCardsScrollViewContent: {
    flexDirection: 'column',
    paddingHorizontal: 50,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchButtonBtn: {
    color: '#000',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
  },
  searchButtonBtn1: {
    borderRadius: 3,
    height: 33,
    width: 58,
  },
  rectangleButtonBtn: {
    borderRadius: 3,
    height: '100%',
    width: '100%',
  },
  bnackgroundPosition: {
    width: 320,
    left: 0,
    position: 'absolute',
  },
  flatlistLayout: {
    maxWidth: 191,
    width: 191,
    borderWidth: 1,
    borderColor: Color.colorSteelblue,
    borderStyle: 'solid',
    backgroundColor: Color.colorGray,
    borderRadius: Border.br_10xs,
    flex: 1,
  },
  frameLayout: {
    height: 90,
    width: 348,
    position: 'absolute',
    overflow: 'hidden',
  },
  searchbarLayout: {
    height: 33,
    position: 'absolute',
  },
  framePosition: {
    left: 0,
    top: 0,
  },
  searchbar1Position: {
    left: '0%',
    bottom: '0%',
    right: '0%',
    top: '0%',
    position: 'absolute',
  },
  atrsPosition: {
    top: '30.3%',
    textAlign: 'left',
    color: Color.colorBlack,
    position: 'absolute',
  },
  logoLayout: {
    height: 34,
    width: 92,
    position: 'absolute',
  },
  flatlist2: {
    marginTop: 8,
  },
  searchresultcards: {
    top: 229,
    backgroundColor: '#f6f6f6',
    maxWidth: 320,
    overflow: 'hidden',
    flex: 1,
    width: 320,
  },
  frameChild: {
    top: 31,
    backgroundColor: '#083549',
    height: 59,
    width: 348,
    left: 0,
    position: 'absolute',
  },
  frame: {
    top: 0,
    left: 0,
  },
  googleAdsChild: {
    left: 46,
    backgroundColor: '#d9d9d9',
    width: 267,
    height: 40,
    top: 0,
    position: 'absolute',
  },
  anuncioDeGoogle: {
    top: 12,
    textAlign: 'left',
    color: Color.colorBlack,
    fontFamily: FontFamily.interRegular,
    fontSize: FontSize.size_xs,
    left: 0,
    position: 'absolute',
  },
  frame1: {
    left: 126,
    width: 108,
    height: 27,
    top: 0,
    position: 'absolute',
    overflow: 'hidden',
  },
  googleAds: {
    top: 516,
    left: -19,
  },
  bnackground: {
    height: 220,
    top: 0,
  },
  searchButton: {
    top: 0,
    position: 'absolute',
  },
  searchbuttoncomponent: {
    left: 236,
    width: 58,
    height: 33,
    top: 162,
    overflow: 'hidden',
  },
  searchbar1: {
    height: '100%',
    borderRadius: Border.br_10xs,
    left: '0%',
    bottom: '0%',
    right: '0%',
    top: '0%',
    width: '100%',
    backgroundColor: Color.colorWhite,
  },
  escribirPalabra: {
    left: '4.27%',
    fontSize: 10,
    fontFamily: FontFamily.interRegular,
    top: '30.3%',
  },
  searchbar: {
    left: 6,
    width: 211,
    top: 162,
  },
  atrs: {
    left: '22.41%',
    fontWeight: '600',
    fontFamily: FontFamily.interSemiBold,
    top: '30.3%',
    fontSize: FontSize.size_xs,
  },
  btngoback: {
    top: 9,
    left: 252,
    width: 58,
    height: 33,
  },
  image1Icon: {
    top: 0,
    left: 0,
  },
  logo: {
    top: 13,
    left: 9,
  },
  busquedaDePalabras: {
    height: 568,
    overflow: 'hidden',
    width: '100%',
    backgroundColor: Color.colorWhite,
    flex: 1,
  },
});
