import { StyleSheet } from 'react-native';
import { Color, FontSize, FontFamily } from '../GlobalStyles';

export const styles = StyleSheet.create({
  rectangleButtonBtn: {
    borderRadius: 3,
    height: '100%',
    width: '100%',
  },
  loremIpsumDolorFlexBox: {
    textAlign: 'left',
    color: Color.colorBlack,
    position: 'absolute',
  },
  acordionLayout: {
    minHeight: 41,
    width: 257,
    left: 27,
    position: 'absolute',
  },
  frameLayout: {
    height: 90,
    width: 348,
    overflow: 'hidden',
  },
  framePosition: {
    top: 0,
    position: 'absolute',
  },
  atrsTypo: {
    fontSize: FontSize.size_xs,
    textAlign: 'left',
    color: Color.colorBlack,
    position: 'absolute',
  },
  childPosition: {
    left: '0%',
    bottom: '0%',
    right: '0%',
    top: '0%',
    position: 'absolute',
  },
  palabraSelecionada: {
    top: 138,
    left: 63,
    fontSize: 20,
    fontFamily: FontFamily.interSemiBold,
    fontWeight: '600',
  },
  singleWordAccordionChild: {
    top: 172,
    left: 113,
    borderStyle: 'solid',
    borderColor: '#0a97d1',
    borderTopWidth: 1,
    width: 85,
    height: 1,
    position: 'absolute',
  },
  atrsTypo1: {
    fontFamily: FontFamily.interSemiBold,
    fontWeight: '600',
  },
  acordionPalabraSelecionada: {
    top: 181,
  },
  acordionPalabraSelecionada1: {
    top: 469,
  },
  singleWordAccordionItem: {
    top: 223,
    backgroundColor: '#f6f6f6',
    width: 256,
    height: 238,
    left: 27,
    position: 'absolute',
  },
  loremIpsumDolor: {
    top: 233,
    left: 42,
    fontSize: 11,
    letterSpacing: 0.3,
    lineHeight: 14,
    width: 232,
    fontFamily: FontFamily.interRegular,
  },
  frameChild: {
    top: 31,
    backgroundColor: Color.colorDarkslategray,
    height: 59,
    left: 0,
    width: 348,
    position: 'absolute',
  },
  frame: {
    left: 0,
    height: 90,
    width: 348,
    overflow: 'hidden',
  },
  googleAdsChild: {
    left: 46,
    backgroundColor: Color.colorGainsboro,
    width: 267,
    height: 40,
  },
  anuncioDeGoogle: {
    top: 12,
    left: 0,
    fontFamily: FontFamily.interRegular,
  },
  frame1: {
    left: 126,
    width: 108,
    height: 27,
    overflow: 'hidden',
  },
  googleAds: {
    top: 516,
    left: -19,
    position: 'absolute',
  },
  tainosInTheRiver1Icon: {
    maxWidth: '100%',
    maxHeight: '100%',
    height: '100%',
    bottom: '0%',
    right: '0%',
    top: '0%',
    width: '100%',
    overflow: 'hidden',
  },
  headermainsinglewordChild: {
    backgroundColor: Color.colorDeepskyblue,
    height: '100%',
    bottom: '0%',
    right: '0%',
    top: '0%',
    width: '100%',
  },
  logoIcon: {
    top: 8,
    left: 10,
    width: 92,
    height: 34,
    position: 'absolute',
  },
  headermainsingleword: {
    width: 320,
    height: 129,
    left: 0,
  },
  atrs: {
    top: '30.3%',
    left: '22.41%',
    fontFamily: FontFamily.interSemiBold,
    fontWeight: '600',
  },
  btngoback: {
    top: 9,
    left: 248,
    width: 58,
    height: 33,
    position: 'absolute',
  },
  singleWordAccordion: {
    backgroundColor: '#fff',
    flex: 1,
    height: 568,
    overflow: 'hidden',
    width: '100%',
  },
});
